keys:
  consumer_key: 'nLIvqw05zincZKXtLTD2MIk8n'
  consumer_secret: 'gtZumt9MSmazRMJsZTChcVD5s0IJ53vxW879oW0FIM1LVCL32m'
  access_token: '597726657-d3xzatGHTEjVsUAzCPN5aIwHAM8iuptuHjB0KSoa'
  access_token_secret: 'Z0R4fLW0aZi3rHWw1YwicfZV0B8oUPPmmNbovQIxwBjiO'